        CPU     8086
        ORG     0h
InterruptVectorTable:
        ; Internal x86 Interrupts:
        dd      0 ; Reserved (Div err)  ; Int 00h
        dd      0 ; Reserved (Step)     ; Int 01h
        dd      0 ; Reserved (NMI)      ; Int 02h
        dd      0 ; Reserved (Break)    ; Int 03h
        dd      0 ; Reserved (Overflow) ; Int 04h
        dd      0                       ; Int 05h
        dd      0                       ; Int 06h
        dd      0                       ; Int 07h
        ; Hardware Interrupts:
        dd      reset ; Reset               ; Int 08h (IRQ 0)
        dd      tick ; Tick                ; Int 09h (IRQ 1)
        dd      keyboard ; Keyboard            ; Int 0Ah (IRQ 2)
        dd      0 ; Simptris Game Over  ; Int 0Bh (IRQ 3)
        dd      0 ; Simptris New Piece  ; Int 0Ch (IRQ 4)
        dd      0 ; Simptris Received   ; Int 0Dh (IRQ 5)
        dd      0 ; Simptris Touchdown  ; Int 0Eh (IRQ 6)
        dd      0 ; Simptris Clear      ; Int 0Fh (IRQ 7)
        ; Software Interrupts:
        dd      0 ; Reserved (PC BIOS)  ; Int 10h
        dd      0                       ; Int 11h
        dd      0                       ; Int 12h
        dd      0                       ; Int 13h
        dd      0                       ; Int 14h
        dd      0                       ; Int 15h
        dd      0                       ; Int 16h
        dd      0                       ; Int 17h
        dd      0                       ; Int 18h
        dd      0                       ; Int 19h
        dd      0                       ; Int 1Ah
        dd      0                       ; Int 1Bh
        dd      0                       ; Int 1Ch
        dd      0                       ; Int 1Dh
        dd      0                       ; Int 1Eh
        dd      0                       ; Int 1Fh
        dd      0                       ; Int 20h
        dd      0 ; Reserved (DOS)      ; Int 21h
        dd      0 ; Simptris Services   ; Int 22h
        dd      0                       ; Int 23h
        dd      0                       ; Int 24h
        dd      0                       ; Int 25h
        dd      0                       ; Int 26h
        dd      0                       ; Int 27h
        dd      0                       ; Int 28h
        dd      0                       ; Int 29h
        dd      0                       ; Int 2Ah
        dd      0                       ; Int 2Bh
        dd      0                       ; Int 2Ch
        dd      0                       ; Int 2Dh
        dd      0                       ; Int 2Eh
        dd      0                       ; Int 2Fh
KeyBuffer:                              ; Address 0xC0
        dw      0
NewPieceType:                           ; Address 0xC2
        dw      0
NewPieceID:                             ; Address 0xC4
        dw      0
NewPieceOrientation:                    ; Address 0xC6
        dw      0
NewPieceColumn:                         ; Address 0xC8
        dw      0
TouchdownID:                            ; Address 0xCA
	dw	0
ScreenBitMap0:                          ; Address 0xCC
        dw      0
ScreenBitMap1:
        dw      0
ScreenBitMap2:
        dw      0
ScreenBitMap3:
        dw      0
ScreenBitMap4:
        dw      0
ScreenBitMap5:
        dw      0
TIMES   100h-($-$$) db  0               ; Fill up to (but not including) address 100h with 0
	jmp	main
; This file contains support routines for 32-bit on the 8086.
; It is intended for use code generated by the C86 compiler.
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
SR_asldiv:			; l1 /= l2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of l1	(was push3)
	push	word [bp+8]	; Push hi l2		(was push1)
	push	word [bp+6]	; Push lo l2		(was push2)
	push	word [bx+2]	; Push hi l1
	push	word [bx]	; Push lo l1
	call	SR_ldiv
	mov	bx,[bp+4]	; Restore l1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_aslmod:			; l1 %= l2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of l1	(was push3)
	push	word [bp+8]	; Push hi l2		(was push1)
	push	word [bp+6]	; Push lo l2		(was push2)
	push	word [bx+2]	; Push hi l1
	push	word [bx]	; Push lo l1
	call	SR_lmod
	mov	bx,[bp+4]	; Restore l1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_aslmul:			; l1 *= l2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of l1	(was push3)
	push	word [bp+8]	; Push hi l2		(was push1)
	push	word [bp+6]	; Push lo l2		(was push2)
	push	word [bx+2]	; Push hi l1
	push	word [bx]	; Push lo l1
	call	SR_lmul
	add	sp,8
	mov	bx,[bp+4]	; Restore l1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_aslshl:			; l1 <<= l2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of l1	(was push3)
	push	word [bp+8]	; Push hi l2		(was push1)
	push	word [bp+6]	; Push lo l2		(was push2)
	push	word [bx+2]	; Push hi l1
	push	word [bx]	; Push lo l1
	call	SR_lshl
	add	sp,8
	mov	bx,[bp+4]	; Restore l1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_aslshr:			; l1 >>= l2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of l1	(was push3)
	push	word [bp+8]	; Push hi l2		(was push1)
	push	word [bp+6]	; Push lo l2		(was push2)
	push	word [bx+2]	; Push hi l1
	push	word [bx]	; Push lo l1
	call	SR_lshr
	add	sp,8
	mov	bx,[bp+4]	; Restore l1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret


SR_asuldiv:			; u1 /= u2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of u1	(was push3)
	push	word [bp+8]	; Push hi u2		(was push1)
	push	word [bp+6]	; Push lo u2		(was push2)
	push	word [bx+2]	; Push hi u1
	push	word [bx]	; Push lo u1
	call	SR_uldiv
	mov	bx,[bp+4]	; Restore u1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_asilmod:			; u1 %= u2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of u1	(was push3)
	push	word [bp+8]	; Push hi u2		(was push1)
	push	word [bp+6]	; Push lo u2		(was push2)
	push	word [bx+2]	; Push hi u1
	push	word [bx]	; Push lo u1
	call	SR_ilmod
	mov	bx,[bp+4]	; Restore u1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_asulmul:			; u1 *= u2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of u1	(was push3)
	push	word [bp+8]	; Push hi u2		(was push1)
	push	word [bp+6]	; Push lo u2		(was push2)
	push	word [bx+2]	; Push hi u1
	push	word [bx]	; Push lo u1
	call	SR_ulmul
	add	sp,8
	mov	bx,[bp+4]	; Restore u1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_asulshl:			; u1 << u2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of u1	(was push3)
	push	word [bp+8]	; Push hi u2		(was push1)
	push	word [bp+6]	; Push lo u2		(was push2)
	push	word [bx+2]	; Push hi u1
	push	word [bx]	; Push lo u1
	call	SR_ulshl
	add	sp,8
	mov	bx,[bp+4]	; Restore u1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_asulshr:			; u1 >> u2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of u1	(was push3)
	push	word [bp+8]	; Push hi u2		(was push1)
	push	word [bp+6]	; Push lo u2		(was push2)
	push	word [bx+2]	; Push hi u1
	push	word [bx]	; Push lo u1
	call	SR_ulshr
	add	sp,8
	mov	bx,[bp+4]	; Restore u1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret


; Main 32-bit routines begin here:

SR_ldiv:	; N_LDIV@
	pop    cx
	push   cs
	push   cx
	; LDIV@
	xor    cx,cx
	jmp    LSR_01
SR_uldiv:	; N_LUDIV@
	pop    cx
	push   cs
	push   cx
	; F_LUDIV@
	mov    cx,0001
	jmp    LSR_01
SR_lmod:	; N_LMOD@
	pop    cx
	push   cs
	push   cx
	; F_LMOD@
	mov    cx,0002
	jmp    LSR_01
SR_ilmod:	; N_LUMOD@
	pop    cx
	push   cs
	push   cx
	; LUMOD@
	mov    cx,0003
LSR_01:
	push   bp
	push   si
	push   di
	mov    bp,sp
	mov    di,cx
	mov    ax,[bp+0Ah]
	mov    dx,[bp+0Ch]
	mov    bx,[bp+0Eh]
	mov    cx,[bp+10h]
	or     cx,cx
	jne    LSR_02
	or     dx,dx
	je     LSR_10
	or     bx,bx
	je     LSR_10
LSR_02:
	test   di,0001
	jne    LSR_04
	or     dx,dx
	jns    LSR_03
	neg    dx
	neg    ax
	sbb    dx,0000
	or     di,000Ch
LSR_03:
	or     cx,cx
	jns    LSR_04
	neg    cx
	neg    bx
	sbb    cx,0000
	xor    di,0004
LSR_04:
	mov    bp,cx
	mov    cx,0020h
	push   di
	xor    di,di
	xor    si,si
LSR_05:
	shl    ax,1
	rcl    dx,1
	rcl    si,1
	rcl    di,1
	cmp    di,bp
	jb     LSR_07
	ja     LSR_06
	cmp    si,bx
	jb     LSR_07
LSR_06:
	sub    si,bx
	sbb    di,bp
	inc    ax
LSR_07:
	loop   LSR_05
	pop    bx
	test   bx,0002
	je     LSR_08
	mov    ax,si
	mov    dx,di
	shr    bx,1
LSR_08:
	test   bx,0004h
	je     LSR_09
	neg    dx
	neg    ax
	sbb    dx,0000
LSR_09:
	pop    di
	pop    si
	pop    bp
	retf   0008
LSR_10:
	div    bx
	test   di,0002
	je     LSR_11
	xchg   dx,ax
LSR_11:
	xor    dx,dx
	jmp    LSR_09
SR_lshl:	; N_LXLSH@
SR_ulshl:
	; r = a << b
	pop    bx
	push   cs
	push   bx

	push   bp
	mov    bp,sp

	push   cx	; C86 doesn't expect use of cx or bx

	mov    ax, [bp+6]	; pop loword(a)
	mov    dx, [bp+8]	; pop hiword(a)
	mov    cx, [bp+10]	; pop word(b)
	
	; LXLSH@
	cmp    cl,10h
	jnb    LSR_12
	mov    bx,ax
	shl    ax,cl
	shl    dx,cl
	neg    cl
	add    cl,10h
	shr    bx,cl
	or     dx,bx
	pop    cx
	pop    bp
	retf
LSR_12:
	sub    cl,10h
	xchg   dx,ax
	xor    ax,ax
	shl    dx,cl
	pop    cx
	pop    bp
	retf
SR_lshr:	; N_LXRSH@
	; r = a >> b
	pop    bx
	push   cs
	push   bx

	push   bp
	mov    bp,sp

	push   cx	; C86 doesn't expect use of cx or bx

        mov    ax, [bp+6]	; pop loword(a)
	mov    dx, [bp+8]	; pop hiword(a)
	mov    cx, [bp+10]	; pop word(b)
	
	; LXRSH@
	cmp    cl,10h
	jnb    LSR_13
	mov    bx,dx
	shr    ax,cl
	sar    dx,cl
	neg    cl
	add    cl,10h
	shl    bx,cl
	or     ax,bx
	pop    cx
	pop    bp
	retf
LSR_13:
	sub    cl,10h
	xchg   dx,ax
	cwd
	sar    ax,cl
	pop    cx
	pop    bp
	retf
SR_ulshr:	; N_LXURSH@
	; r = a >> b
	pop    bx
	push   cs
	push   bx

	push   bp
	mov    bp,sp

	push   cx	; C86 doesn't expect use of cx or bx

        mov    ax, [bp+6]	; pop loword(a)
	mov    dx, [bp+8]	; pop hiword(a)
	mov    cx, [bp+10]	; pop word(b)
	
	; LXURSH@
	cmp    cl,10h
	jnb    LSR_14
	mov    bx,dx
	shr    ax,cl
	shr    dx,cl
	neg    cl
	add    cl,10h
	shl    bx,cl
	or     ax,bx
	pop    cx
	pop    bp
	retf
LSR_14:
	sub    cl,10h
	xchg   dx,ax
	xor    dx,dx
	shr    ax,cl
	pop    cx
	pop    bp
	retf
SR_lmul:	; N_LXMUL@
SR_ulmul:
	; r = a * b
	push   bp
	push   si
	mov    bp,sp

	push   cx	; C86 doesn't expect use of cx or bx
	push   bx

        mov    bx, [bp+6]	; pop loword(a)
	mov    cx, [bp+8]	; pop hiword(a)
	mov    ax, [bp+10]	; pop loword(b)
	mov    dx, [bp+12]	; pop hiword(b)
	
	xchg   si,ax
	xchg   dx,ax
	test   ax,ax
	je     LSR_15
	mul    bx
LSR_15:
	jcxz   LSR_16
	xchg   cx,ax
	mul    si
	add    ax,cx
LSR_16:
	xchg   si,ax
	mul    bx
	add    dx,si
	pop    bx
	pop    cx
	pop    si
	pop    bp
	ret

; Generated by c86 (BYU-NASM) 5.1 (beta) from clib.c
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
new_line:
	db	13,10,36
	ALIGN	2
signalEOI:
	jmp	L_clib_1
L_clib_2:
	mov	al, 0x20
	out	0x20, al
	mov	sp, bp
	pop	bp
	ret
L_clib_1:
	push	bp
	mov	bp, sp
	jmp	L_clib_2
	ALIGN	2
exit:
	jmp	L_clib_4
L_clib_5:
	mov	ah, 4Ch
	mov	al, [bp+4]
	int	21h
	mov	sp, bp
	pop	bp
	ret
L_clib_4:
	push	bp
	mov	bp, sp
	jmp	L_clib_5
	ALIGN	2
print:
	jmp	L_clib_7
L_clib_8:
	mov	ah, 40h
	mov	bx, 1
	mov	cx, [bp+6]
	mov	dx, [bp+4]
	int	21h
	mov	sp, bp
	pop	bp
	ret
L_clib_7:
	push	bp
	mov	bp, sp
	jmp	L_clib_8
	ALIGN	2
printChar:
	jmp	L_clib_10
L_clib_11:
	mov	ah, 2
	mov	dl, [bp+4]
	int	21h
	mov	sp, bp
	pop	bp
	ret
L_clib_10:
	push	bp
	mov	bp, sp
	jmp	L_clib_11
	ALIGN	2
printNewLine:
	jmp	L_clib_13
L_clib_14:
	mov	ah, 9
	mov	dx, new_line
	int	21h
	mov	sp, bp
	pop	bp
	ret
L_clib_13:
	push	bp
	mov	bp, sp
	jmp	L_clib_14
	ALIGN	2
printString:
	jmp	L_clib_16
L_clib_17:
	xor	si,si
	mov	bx, [bp+4]
	jmp	printString2
	printString1:
	inc	si
	printString2:
	cmp	byte [bx+si],0
	jne	printString1
	mov	dx, bx
	mov	cx, si
	mov	ah, 40h
	mov	bx, 1
	int	21h
	mov	sp, bp
	pop	bp
	ret
L_clib_16:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_clib_17
	ALIGN	2
printInt:
	jmp	L_clib_19
L_clib_20:
	mov	word [bp-2], 0
	mov	word [bp-4], 10000
	cmp	word [bp+4], 0
	jge	L_clib_21
	mov	byte [bp-10], 45
	inc	word [bp-2]
	mov	ax, word [bp+4]
	neg	ax
	mov	word [bp+4], ax
L_clib_21:
	mov	ax, word [bp+4]
	test	ax, ax
	jne	L_clib_22
	mov	word [bp-4], 1
	jmp	L_clib_23
L_clib_22:
	jmp	L_clib_25
L_clib_24:
	mov	ax, word [bp-4]
	cwd
	mov	cx, 10
	idiv	cx
	mov	word [bp-4], ax
L_clib_25:
	mov	ax, word [bp+4]
	cwd
	idiv	word [bp-4]
	test	ax, ax
	je	L_clib_24
L_clib_26:
L_clib_23:
	jmp	L_clib_28
L_clib_27:
	mov	ax, word [bp+4]
	xor	dx, dx
	div	word [bp-4]
	add	al, 48
	mov	si, word [bp-2]
	lea	dx, [bp-10]
	add	si, dx
	mov	byte [si], al
	inc	word [bp-2]
	mov	ax, word [bp+4]
	xor	dx, dx
	div	word [bp-4]
	mov	ax, dx
	mov	word [bp+4], ax
	mov	ax, word [bp-4]
	cwd
	mov	cx, 10
	idiv	cx
	mov	word [bp-4], ax
	mov	ax, word [bp-4]
	mov	word [bp-4], ax
L_clib_28:
	cmp	word [bp-4], 0
	jg	L_clib_27
L_clib_29:
	push	word [bp-2]
	lea	ax, [bp-10]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_19:
	push	bp
	mov	bp, sp
	sub	sp, 10
	jmp	L_clib_20
	ALIGN	2
printLong:
	jmp	L_clib_31
L_clib_32:
	mov	word [bp-2], 0
	mov	word [bp-6], 51712
	mov	word [bp-4], 15258
	cmp	word [bp+6], 0
	jg	L_clib_33
	jl	L_clib_34
	cmp	word [bp+4], 0
	jae	L_clib_33
L_clib_34:
	mov	byte [bp-17], 45
	inc	word [bp-2]
	mov	ax, word [bp+4]
	mov	dx, word [bp+6]
	neg	ax
	adc	dx, 0
	neg	dx
	mov	word [bp+4], ax
	mov	word [bp+6], dx
L_clib_33:
	mov	ax, word [bp+4]
	mov	dx, word [bp+6]
	or	dx, ax
	jne	L_clib_35
	mov	word [bp-6], 1
	mov	word [bp-4], 0
	jmp	L_clib_36
L_clib_35:
	jmp	L_clib_38
L_clib_37:
	mov	ax, 10
	xor	dx, dx
	push	dx
	push	ax
	lea	ax, [bp-6]
	push	ax
	call	SR_asldiv
L_clib_38:
	push	word [bp-4]
	push	word [bp-6]
	push	word [bp+6]
	push	word [bp+4]
	call	SR_ldiv
	or	dx, ax
	je	L_clib_37
L_clib_39:
L_clib_36:
	jmp	L_clib_41
L_clib_40:
	push	word [bp-4]
	push	word [bp-6]
	push	word [bp+6]
	push	word [bp+4]
	call	SR_uldiv
	add	al, 48
	mov	si, word [bp-2]
	lea	dx, [bp-17]
	add	si, dx
	mov	byte [si], al
	inc	word [bp-2]
	push	word [bp-4]
	push	word [bp-6]
	push	word [bp+6]
	push	word [bp+4]
	call	SR_lmod
	mov	word [bp+4], ax
	mov	word [bp+6], dx
	mov	ax, 10
	xor	dx, dx
	push	dx
	push	ax
	lea	ax, [bp-6]
	push	ax
	call	SR_asldiv
L_clib_41:
	cmp	word [bp-4], 0
	jg	L_clib_40
	jne	L_clib_43
	cmp	word [bp-6], 0
	ja	L_clib_40
L_clib_43:
L_clib_42:
	push	word [bp-2]
	lea	ax, [bp-17]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_31:
	push	bp
	mov	bp, sp
	sub	sp, 18
	jmp	L_clib_32
	ALIGN	2
printUInt:
	jmp	L_clib_45
L_clib_46:
	mov	word [bp-2], 0
	mov	word [bp-4], 10000
	mov	ax, word [bp+4]
	test	ax, ax
	jne	L_clib_47
	mov	word [bp-4], 1
	jmp	L_clib_48
L_clib_47:
	jmp	L_clib_50
L_clib_49:
	mov	ax, word [bp-4]
	xor	dx, dx
	mov	cx, 10
	div	cx
	mov	word [bp-4], ax
L_clib_50:
	mov	ax, word [bp+4]
	xor	dx, dx
	div	word [bp-4]
	test	ax, ax
	je	L_clib_49
L_clib_51:
L_clib_48:
	jmp	L_clib_53
L_clib_52:
	mov	ax, word [bp+4]
	xor	dx, dx
	div	word [bp-4]
	add	al, 48
	mov	si, word [bp-2]
	lea	dx, [bp-10]
	add	si, dx
	mov	byte [si], al
	inc	word [bp-2]
	mov	ax, word [bp+4]
	xor	dx, dx
	div	word [bp-4]
	mov	word [bp+4], dx
	mov	ax, word [bp-4]
	xor	dx, dx
	mov	cx, 10
	div	cx
	mov	word [bp-4], ax
L_clib_53:
	mov	ax, word [bp-4]
	test	ax, ax
	jne	L_clib_52
L_clib_54:
	push	word [bp-2]
	lea	ax, [bp-10]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_45:
	push	bp
	mov	bp, sp
	sub	sp, 10
	jmp	L_clib_46
	ALIGN	2
printULong:
	jmp	L_clib_56
L_clib_57:
	mov	word [bp-2], 0
	mov	word [bp-6], 51712
	mov	word [bp-4], 15258
	mov	ax, word [bp+4]
	mov	dx, word [bp+6]
	or	dx, ax
	jne	L_clib_58
	mov	word [bp-6], 1
	mov	word [bp-4], 0
	jmp	L_clib_59
L_clib_58:
	jmp	L_clib_61
L_clib_60:
	mov	ax, 10
	xor	dx, dx
	push	dx
	push	ax
	lea	ax, [bp-6]
	push	ax
	call	SR_asuldiv
L_clib_61:
	push	word [bp-4]
	push	word [bp-6]
	push	word [bp+6]
	push	word [bp+4]
	call	SR_uldiv
	or	dx, ax
	je	L_clib_60
L_clib_62:
L_clib_59:
	jmp	L_clib_64
L_clib_63:
	push	word [bp-4]
	push	word [bp-6]
	push	word [bp+6]
	push	word [bp+4]
	call	SR_uldiv
	add	al, 48
	mov	si, word [bp-2]
	lea	dx, [bp-17]
	add	si, dx
	mov	byte [si], al
	inc	word [bp-2]
	push	word [bp-4]
	push	word [bp-6]
	lea	ax, [bp+4]
	push	ax
	call	SR_asilmod
	mov	ax, 10
	xor	dx, dx
	push	dx
	push	ax
	lea	ax, [bp-6]
	push	ax
	call	SR_asuldiv
L_clib_64:
	mov	ax, word [bp-6]
	mov	dx, word [bp-4]
	or	dx, ax
	jne	L_clib_63
L_clib_65:
	push	word [bp-2]
	lea	ax, [bp-17]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_56:
	push	bp
	mov	bp, sp
	sub	sp, 18
	jmp	L_clib_57
	ALIGN	2
printByte:
	jmp	L_clib_67
L_clib_68:
	mov	al, byte [bp+4]
	cbw
	mov	cx, 4
	sar	ax, cl
	and	ax, 15
	mov	byte [bp-1], al
	cmp	byte [bp-1], 9
	jle	L_clib_69
	mov	al, byte [bp-1]
	cbw
	sub	ax, 10
	add	ax, 65
	jmp	L_clib_70
L_clib_69:
	mov	al, byte [bp-1]
	cbw
	add	ax, 48
L_clib_70:
	mov	byte [bp-3], al
	mov	al, byte [bp+4]
	and	al, 15
	mov	byte [bp-1], al
	cmp	byte [bp-1], 9
	jle	L_clib_71
	mov	al, byte [bp-1]
	cbw
	sub	ax, 10
	add	ax, 65
	jmp	L_clib_72
L_clib_71:
	mov	al, byte [bp-1]
	cbw
	add	ax, 48
L_clib_72:
	mov	byte [bp-2], al
	mov	ax, 2
	push	ax
	lea	ax, [bp-3]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_67:
	push	bp
	mov	bp, sp
	sub	sp, 4
	jmp	L_clib_68
	ALIGN	2
printWord:
	jmp	L_clib_74
L_clib_75:
	mov	word [bp-2], 3
	jmp	L_clib_77
L_clib_76:
	mov	ax, word [bp+4]
	and	ax, 15
	mov	byte [bp-3], al
	cmp	byte [bp-3], 9
	jle	L_clib_80
	mov	al, byte [bp-3]
	cbw
	sub	ax, 10
	add	ax, 65
	jmp	L_clib_81
L_clib_80:
	mov	al, byte [bp-3]
	cbw
	add	ax, 48
L_clib_81:
	mov	si, word [bp-2]
	lea	dx, [bp-7]
	add	si, dx
	mov	byte [si], al
	mov	ax, word [bp+4]
	mov	cx, 4
	sar	ax, cl
	mov	word [bp+4], ax
L_clib_79:
	dec	word [bp-2]
L_clib_77:
	cmp	word [bp-2], 0
	jge	L_clib_76
L_clib_78:
	mov	ax, 4
	push	ax
	lea	ax, [bp-7]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_74:
	push	bp
	mov	bp, sp
	sub	sp, 8
	jmp	L_clib_75
	ALIGN	2
printDWord:
	jmp	L_clib_83
L_clib_84:
	lea	ax, [bp+4]
	mov	si, ax
	mov	ax, word [si]
	mov	word [bp-6], ax
	lea	ax, [bp+4]
	mov	si, ax
	add	si, 2
	mov	ax, word [si]
	mov	word [bp-8], ax
	mov	word [bp-2], 3
	jmp	L_clib_86
L_clib_85:
	mov	ax, word [bp-6]
	and	ax, 15
	mov	byte [bp-3], al
	cmp	byte [bp-3], 9
	jle	L_clib_89
	mov	al, byte [bp-3]
	cbw
	sub	ax, 10
	add	ax, 65
	jmp	L_clib_90
L_clib_89:
	mov	al, byte [bp-3]
	cbw
	add	ax, 48
L_clib_90:
	mov	dx, word [bp-2]
	add	dx, 4
	mov	si, dx
	lea	dx, [bp-16]
	add	si, dx
	mov	byte [si], al
	mov	ax, word [bp-6]
	mov	cx, 4
	sar	ax, cl
	mov	word [bp-6], ax
	mov	ax, word [bp-8]
	and	ax, 15
	mov	byte [bp-3], al
	cmp	byte [bp-3], 9
	jle	L_clib_91
	mov	al, byte [bp-3]
	cbw
	sub	ax, 10
	add	ax, 65
	jmp	L_clib_92
L_clib_91:
	mov	al, byte [bp-3]
	cbw
	add	ax, 48
L_clib_92:
	mov	si, word [bp-2]
	lea	dx, [bp-16]
	add	si, dx
	mov	byte [si], al
	mov	ax, word [bp-8]
	mov	cx, 4
	sar	ax, cl
	mov	word [bp-8], ax
L_clib_88:
	dec	word [bp-2]
L_clib_86:
	cmp	word [bp-2], 0
	jge	L_clib_85
L_clib_87:
	mov	ax, 8
	push	ax
	lea	ax, [bp-16]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_83:
	push	bp
	mov	bp, sp
	sub	sp, 16
	jmp	L_clib_84

reset:
	;Step 1
	push ax
	push bx
	push cx
	push dx
	push bp
	mov bp, sp

	;Step 2
	sti

	;Step 3
	mov ax, 0
	push ax
	call exit

	;Step 4
	cli

	;Step 5
	mov	al, 0x20	; Load nonspecific EOI value (0x20) into register al
	out	0x20, al	; Write EOI to PIC (port 0x20)

	;Step 6
	pop bp
	pop dx
	pop cx
	pop bx
	pop ax

	;Step 7
	iret

tick:
	;Step 1
	push 	bp
	push 	ax
	push 	bx
	push 	cx
	push 	dx
	push 	si
	push 	di
	push 	es
	push 	ds
	;mov bp, sp
	;call pushed

	call YKEnterISR
	;Step 2
	sti

	;Step 3	mov bp, sp
	call YKTickHandler
	call tickHandler


	;Step 4
	cli

	;Step 5
	mov	al, 0x20	; Load nonspecific EOI value (0x20) into register al
	out	0x20, al	; Write EOI to PIC (port 0x20)

	call YKExitISR

	;Step 6
	pop		ds
	pop 	es
	pop 	di
	pop 	si
 	pop 	dx
	pop 	cx
  pop 	bx
  pop 	ax
	pop 	bp
	;call popped
	iret

keyboard:
	;Step 1
	push 	bp
	push 	ax
	push 	bx
	push 	cx
	push 	dx
	push 	si
	push 	di
	push 	es
	push 	ds
	;mov bp, sp
	;call pushed

	call YKEnterISR
	;Step 2

	sti
	;Step 3
	call keyboardHandler

	;Step 4
	cli

	;Step 5
	mov	al, 0x20	; Load nonspecific EOI value (0x20) into register al
	out	0x20, al	; Write EOI to PIC (port 0x20)

	call YKExitISR

	;Step 6
	pop		ds
	pop 	es
	pop 	di
	pop 	si
 	pop 	dx
	pop 	cx
  pop 	bx
  pop 	ax
	pop 	bp
	;call popped
	;Step 7
	iret
; Generated by c86 (BYU-NASM) 5.1 (beta) from myinth.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
	ALIGN	2
ticks:
	DW	0
L_myinth_1:
	DW	0
L_myinth_2:
	DW	0
L_myinth_3:
	DB	"  TickISR: queue overflow! ",0xA,0
	ALIGN	2
tickHandler:
	; >>>>> Line:	12
	; >>>>> { 
	jmp	L_myinth_4
L_myinth_5:
	; >>>>> Line:	17
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	18
	; >>>>> val = ++ticks; 
	mov	ax, word [ticks]
	inc	ax
	mov	word [ticks], ax
	mov	word [bp-2], ax
	; >>>>> Line:	19
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	23
	; >>>>> MsgArray[next].tick = YKTickNum; 
	mov	ax, word [L_myinth_1]
	shl	ax, 1
	shl	ax, 1
	mov	si, ax
	add	si, MsgArray
	mov	ax, word [YKTickNum]
	mov	word [si], ax
	; >>>>> Line:	24
	; >>>>> data = (data + 89) % 100; 
	mov	ax, word [L_myinth_2]
	add	ax, 89
	cwd
	mov	cx, 100
	idiv	cx
	mov	ax, dx
	mov	word [L_myinth_2], ax
	; >>>>> Line:	25
	; >>>>> MsgArray[next].data = data; 
	mov	ax, word [L_myinth_1]
	shl	ax, 1
	shl	ax, 1
	add	ax, MsgArray
	mov	si, ax
	add	si, 2
	mov	ax, word [L_myinth_2]
	mov	word [si], ax
	; >>>>> Line:	26
	; >>>>> if (YKQPost(MsgQPtr, (void *) &(MsgArray[next])) == 0) 
	mov	ax, word [L_myinth_1]
	shl	ax, 1
	shl	ax, 1
	add	ax, MsgArray
	push	ax
	push	word [MsgQPtr]
	call	YKQPost
	add	sp, 4
	test	ax, ax
	jne	L_myinth_6
	; >>>>> Line:	28
	; >>>>> printString("  TickISR: queue overflow! \n"); 
	mov	ax, L_myinth_3
	push	ax
	call	printString
	add	sp, 2
	jmp	L_myinth_7
L_myinth_6:
	; >>>>> Line:	30
	; >>>>> else if (++next >= 20) 
	mov	ax, word [L_myinth_1]
	inc	ax
	mov	word [L_myinth_1], ax
	cmp	ax, 20
	jl	L_myinth_8
	; >>>>> Line:	32
	; >>>>> next = 0; 
	mov	word [L_myinth_1], 0
L_myinth_8:
L_myinth_7:
	mov	sp, bp
	pop	bp
	ret
L_myinth_4:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_myinth_5
	ALIGN	2
keyboardHandler:
	; >>>>> Line:	37
	; >>>>> { 
	jmp	L_myinth_10
L_myinth_11:
	; >>>>> Line:	38
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	39
	; >>>>> GlobalFlag = 1; 
	mov	word [GlobalFlag], 1
	; >>>>> Line:	40
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	mov	sp, bp
	pop	bp
	ret
L_myinth_10:
	push	bp
	mov	bp, sp
	jmp	L_myinth_11
; Generated by c86 (BYU-NASM) 5.1 (beta) from yakc.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
	ALIGN	2
FLAGS_MASK:
	DW	512
YKInterruptDepth:
	DW	0
kernelStarted:
	DW	0
readyToStart:
	DB	0
runningTask:
	DB	0
firstTime:
	DB	1
	ALIGN	2
pushedLevel:
	DW	0
contextSaved:
	DB	0
	ALIGN	2
semIndex:
	DW	0
qIndex:
	DW	0
	ALIGN	2
YKInitialize:
	; >>>>> Line:	36
	; >>>>> { 
	jmp	L_yakc_1
L_yakc_2:
	; >>>>> Line:	38
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	40
	; >>>>> for (i = 0; i < 5; ++i) 
	mov	word [bp-2], 0
	jmp	L_yakc_4
L_yakc_3:
	; >>>>> Line:	42
	; >>>>> YKTCBArray[i].prior 
	mov	ax, word [bp-2]
	mov	cx, 14
	imul	cx
	add	ax, YKTCBArray
	mov	si, ax
	add	si, 6
	mov	byte [si], 100
	; >>>>> Line:	43
	; >>>>> YKTCBArray[i].inUse = 0; 
	mov	ax, word [bp-2]
	mov	cx, 14
	imul	cx
	add	ax, YKTCBArray
	mov	si, ax
	add	si, 12
	mov	byte [si], 0
L_yakc_6:
	inc	word [bp-2]
L_yakc_4:
	cmp	word [bp-2], 5
	jl	L_yakc_3
L_yakc_5:
	; >>>>> Line:	46
	; >>>>> YKNewTask(YKIdleTask, (void *)&IdleStk[256], 99); 
	mov	al, 99
	push	ax
	mov	ax, (IdleStk+512)
	push	ax
	mov	ax, YKIdleTask
	push	ax
	call	YKNewTask
	add	sp, 6
	; >>>>> Line:	47
	; >>>>> readyToStart = 0; 
	mov	byte [readyToStart], 0
	mov	sp, bp
	pop	bp
	ret
L_yakc_1:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_2
L_yakc_8:
	DB	"Pushed: ",0
	ALIGN	2
pushed:
	; >>>>> Line:	50
	; >>>>> { 
	jmp	L_yakc_9
L_yakc_10:
	; >>>>> Line:	51
	; >>>>> pushedLevel = pushedLevel + 1; 
	mov	ax, word [pushedLevel]
	inc	ax
	mov	word [pushedLevel], ax
	; >>>>> Line:	52
	; >>>>> printString("Pushed: "); 
	mov	ax, L_yakc_8
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	53
	; >>>>> printInt(pushedLevel); 
	push	word [pushedLevel]
	call	printInt
	add	sp, 2
	; >>>>> Line:	54
	; >>>>> printNewLine(); 
	call	printNewLine
	mov	sp, bp
	pop	bp
	ret
L_yakc_9:
	push	bp
	mov	bp, sp
	jmp	L_yakc_10
L_yakc_12:
	DB	"Popped: ",0
	ALIGN	2
popped:
	; >>>>> Line:	58
	; >>>>> { 
	jmp	L_yakc_13
L_yakc_14:
	; >>>>> Line:	59
	; >>>>> pushedLevel = pushedLevel - 1; 
	mov	ax, word [pushedLevel]
	dec	ax
	mov	word [pushedLevel], ax
	; >>>>> Line:	60
	; >>>>> printString("Popped: "); 
	mov	ax, L_yakc_12
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	61
	; >>>>> printInt(pushedLevel); 
	push	word [pushedLevel]
	call	printInt
	add	sp, 2
	; >>>>> Line:	62
	; >>>>> printNewLine(); 
	call	printNewLine
	mov	sp, bp
	pop	bp
	ret
L_yakc_13:
	push	bp
	mov	bp, sp
	jmp	L_yakc_14
	ALIGN	2
YKIdleTask:
	; >>>>> Line:	66
	; >>>>> { 
	jmp	L_yakc_16
L_yakc_17:
	; >>>>> Line:	67
	; >>>>> while(1) 
	jmp	L_yakc_19
L_yakc_18:
	; >>>>> Line:	69
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	70
	; >>>>> ++YKIdleCount; 
	inc	word [YKIdleCount]
	; >>>>> Line:	71
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
L_yakc_19:
	jmp	L_yakc_18
L_yakc_20:
	mov	sp, bp
	pop	bp
	ret
L_yakc_16:
	push	bp
	mov	bp, sp
	jmp	L_yakc_17
	ALIGN	2
YKNewTask:
	; >>>>> Line:	76
	; >>>>> { 
	jmp	L_yakc_22
L_yakc_23:
	; >>>>> Line:	78
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	80
	; >>>>> for (i = 0; i <= 5; ++i) 
	mov	word [bp-2], 0
	jmp	L_yakc_25
L_yakc_24:
	; >>>>> Line:	82
	; >>>>> if (!YKTCBArray[i].inUse) 
	mov	ax, word [bp-2]
	mov	cx, 14
	imul	cx
	add	ax, YKTCBArray
	mov	si, ax
	add	si, 12
	mov	al, byte [si]
	test	al, al
	jne	L_yakc_28
	; >>>>> Line:	83
	; >>>>> break; 
	jmp	L_yakc_26
L_yakc_28:
L_yakc_27:
	inc	word [bp-2]
L_yakc_25:
	cmp	word [bp-2], 5
	jle	L_yakc_24
L_yakc_26:
	; >>>>> Line:	86
	; >>>>> YKTCBArray[i].ip = (unsigned int) task; 
	mov	ax, word [bp-2]
	mov	cx, 14
	imul	cx
	mov	si, ax
	add	si, YKTCBArray
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	87
	; >>>>> YKTCBArray[i].stackptr = taskStack; 
	mov	ax, word [bp-2]
	mov	cx, 14
	imul	cx
	add	ax, YKTCBArray
	mov	si, ax
	add	si, 2
	mov	ax, word [bp+6]
	mov	word [si], ax
	; >>>>> Line:	88
	; >>>>> YKTCBArray[i].state = READY; 
	mov	ax, word [bp-2]
	mov	cx, 14
	imul	cx
	add	ax, YKTCBArray
	mov	si, ax
	add	si, 4
	mov	word [si], 3
	; >>>>> Line:	89
	; >>>>> YKTCBArray[i].delay = 0; 
	mov	ax, word [bp-2]
	mov	cx, 14
	imul	cx
	add	ax, YKTCBArray
	mov	si, ax
	add	si, 8
	mov	word [si], 0
	; >>>>> Line:	90
	; >>>>> YKTCBArray[i].inUse = 1; 
	mov	ax, word [bp-2]
	mov	cx, 14
	imul	cx
	add	ax, YKTCBArray
	mov	si, ax
	add	si, 12
	mov	byte [si], 1
	; >>>>> Line:	91
	; >>>>> YKTCBArray[i].priority = priority; 
	mov	ax, word [bp-2]
	mov	cx, 14
	imul	cx
	add	ax, YKTCBArray
	mov	si, ax
	add	si, 6
	mov	al, byte [bp+8]
	mov	byte [si], al
	; >>>>> Line:	92
	; >>>>> YKCreateContext(YKTCBArray[i].stackptr, YKTCBArray[i].ip); 
	mov	ax, word [bp-2]
	mov	cx, 14
	imul	cx
	mov	si, ax
	add	si, YKTCBArray
	push	word [si]
	mov	ax, word [bp-2]
	mov	cx, 14
	imul	cx
	add	ax, YKTCBArray
	mov	si, ax
	add	si, 2
	push	word [si]
	call	YKCreateContext
	add	sp, 4
	; >>>>> Line:	93
	; >>>>> YKTCBArray[i].stackptr += 24; 
	mov	ax, word [bp-2]
	mov	cx, 14
	imul	cx
	add	ax, YKTCBArray
	mov	si, ax
	add	si, 2
	add	word [si], -24
	; >>>>> Line:	94
	; >>>>> readyToStart = 1; 
	mov	byte [readyToStart], 1
	; >>>>> Line:	96
	; >>>>> if(kernelStarted) 
	mov	ax, word [kernelStarted]
	test	ax, ax
	je	L_yakc_29
	; >>>>> Line:	98
	; >>>>> currentTask = &YKTCBArray[i]; 
	mov	ax, word [bp-2]
	mov	cx, 14
	imul	cx
	add	ax, YKTCBArray
	mov	word [currentTask], ax
	; >>>>> Line:	99
	; >>>>> contextSaved = 0; 
	mov	byte [contextSaved], 0
	; >>>>> Line:	100
	; >>>>> YKScheduler(); 
	call	YKScheduler
L_yakc_29:
	mov	sp, bp
	pop	bp
	ret
L_yakc_22:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_23
	ALIGN	2
YKRun:
	; >>>>> Line:	106
	; >>>>> { 
	jmp	L_yakc_31
L_yakc_32:
	; >>>>> Line:	107
	; >>>>> if (kernelStarted || !readyToStart) 
	mov	ax, word [kernelStarted]
	test	ax, ax
	jne	L_yakc_34
	mov	al, byte [readyToStart]
	test	al, al
	jne	L_yakc_33
L_yakc_34:
	; >>>>> Line:	108
	; >>>>> return; 
	jmp	L_yakc_35
L_yakc_33:
	; >>>>> Line:	111
	; >>>>> kernelStarted = 1; 
	mov	word [kernelStarted], 1
	; >>>>> Line:	113
	; >>>>> contextSaved = 0; 
	mov	byte [contextSaved], 0
	; >>>>> Line:	114
	; >>>>> YKScheduler(); 
	call	YKScheduler
	; >>>>> Line:	115
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
L_yakc_35:
	mov	sp, bp
	pop	bp
	ret
L_yakc_31:
	push	bp
	mov	bp, sp
	jmp	L_yakc_32
	ALIGN	2
YKScheduler:
	; >>>>> Line:	119
	; >>>>> { 
	jmp	L_yakc_37
L_yakc_38:
	; >>>>> Line:	124
	; >>>>> if (!kernelStarted) return; 
	mov	byte [bp-3], 100
	mov	byte [bp-4], 0
	; >>>>> Line:	124
	; >>>>> if (!kernelStarted) return; 
	mov	ax, word [kernelStarted]
	test	ax, ax
	jne	L_yakc_39
	; >>>>> Line:	124
	; >>>>> if (!kernelStarted) return; 
	jmp	L_yakc_40
L_yakc_39:
	; >>>>> Line:	126
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	128
	; >>>>> for (i = 0; i <= 5; ++i) 
	mov	word [bp-2], 0
	jmp	L_yakc_42
L_yakc_41:
	; >>>>> Line:	130
	; >>>>> if (!YKTCBArray[i].inUse) 
	mov	ax, word [bp-2]
	mov	cx, 14
	imul	cx
	add	ax, YKTCBArray
	mov	si, ax
	add	si, 12
	mov	al, byte [si]
	test	al, al
	jne	L_yakc_45
	; >>>>> Line:	131
	; >>>>> break; 
	jmp	L_yakc_43
L_yakc_45:
	; >>>>> Line:	132
	; >>>>> if (YKTCBArray[i].priority < maxPriority && YKTCBArray[i].state == READY) 
	mov	ax, word [bp-2]
	mov	cx, 14
	imul	cx
	add	ax, YKTCBArray
	mov	si, ax
	add	si, 6
	mov	al, byte [si]
	cbw
	mov	dl, byte [bp-3]
	xor	dh, dh
	cmp	dx, ax
	jle	L_yakc_46
	mov	ax, word [bp-2]
	mov	cx, 14
	imul	cx
	add	ax, YKTCBArray
	mov	si, ax
	add	si, 4
	cmp	word [si], 3
	jne	L_yakc_46
	; >>>>> Line:	134
	; >>>>> maxPriority = YKTCBArray[i].priority; 
	mov	ax, word [bp-2]
	mov	cx, 14
	imul	cx
	add	ax, YKTCBArray
	mov	si, ax
	add	si, 6
	mov	al, byte [si]
	mov	byte [bp-3], al
	; >>>>> Line:	135
	; >>>>> toRun = i; 
	mov	al, byte [bp-2]
	mov	byte [bp-4], al
L_yakc_46:
L_yakc_44:
	inc	word [bp-2]
L_yakc_42:
	cmp	word [bp-2], 5
	jle	L_yakc_41
L_yakc_43:
	; >>>>> Line:	138
	; >>>>> nextTask = &YKTCBAr 
	mov	al, byte [bp-4]
	xor	ah, ah
	mov	cx, 14
	imul	cx
	add	ax, YKTCBArray
	mov	word [nextTask], ax
	; >>>>> Line:	140
	; >>>>> if (runningTask == toRun && !firstTime) 
	mov	al, byte [bp-4]
	cmp	al, byte [runningTask]
	jne	L_yakc_47
	mov	al, byte [firstTime]
	test	al, al
	jne	L_yakc_47
	; >>>>> Line:	143
	; >>>>> return; 
	jmp	L_yakc_40
L_yakc_47:
	; >>>>> Line:	145
	; >>>>> if(firstTime) { 
	mov	al, byte [firstTime]
	test	al, al
	je	L_yakc_48
	; >>>>> Line:	146
	; >>>>> firstTime = 0; 
	mov	byte [firstTime], 0
	; >>>>> Line:	147
	; >>>>> currentTask = &YKTCBArray[toRun]; 
	mov	al, byte [bp-4]
	xor	ah, ah
	mov	cx, 14
	imul	cx
	add	ax, YKTCBArray
	mov	word [currentTask], ax
	; >>>>> Line:	148
	; >>>>> runningTask = toRun; 
	mov	al, byte [bp-4]
	mov	byte [runningTask], al
	; >>>>> Line:	149
	; >>>>> YKDispatcherFirst(); 
	call	YKDispatcherFirst
	jmp	L_yakc_49
L_yakc_48:
	; >>>>> Line:	153
	; >>>>> ++YKCtxSwCount; 
	inc	word [YKCtxSwCount]
	; >>>>> Line:	154
	; >>>>> currentTask = &YKTCBArray[runningTask]; 
	mov	al, byte [runningTask]
	xor	ah, ah
	mov	cx, 14
	imul	cx
	add	ax, YKTCBArray
	mov	word [currentTask], ax
	; >>>>> Line:	155
	; >>>>> runningTask = toRun; 
	mov	al, byte [bp-4]
	mov	byte [runningTask], al
	; >>>>> Line:	156
	; >>>>> if(contextSaved) 
	mov	al, byte [contextSaved]
	test	al, al
	je	L_yakc_50
	; >>>>> Line:	158
	; >>>>> contextSaved = 0; 
	mov	byte [contextSaved], 0
	; >>>>> Line:	159
	; >>>>> YKDispatcherNoSave(); 
	call	YKDispatcherNoSave
	jmp	L_yakc_51
L_yakc_50:
	; >>>>> Line:	163
	; >>>>> YKDispatcher(); 
	call	YKDispatcher
L_yakc_51:
L_yakc_49:
L_yakc_40:
	mov	sp, bp
	pop	bp
	ret
L_yakc_37:
	push	bp
	mov	bp, sp
	sub	sp, 4
	jmp	L_yakc_38
	ALIGN	2
YKDelayTask:
	; >>>>> Line:	170
	; >>>>> { 
	jmp	L_yakc_53
L_yakc_54:
	; >>>>> Line:	171
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	173
	; >>>>> YKTCBArray[runningTask].delay = count; 
	mov	al, byte [runningTask]
	xor	ah, ah
	mov	cx, 14
	imul	cx
	add	ax, YKTCBArray
	mov	si, ax
	add	si, 8
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	174
	; >>>>> YKTCBArray[runningTa 
	mov	al, byte [runningTask]
	xor	ah, ah
	mov	cx, 14
	imul	cx
	add	ax, YKTCBArray
	mov	si, ax
	add	si, 4
	mov	word [si], 1
	; >>>>> Line:	175
	; >>>>> contextSaved = 0; 
	mov	byte [contextSaved], 0
	; >>>>> Line:	176
	; >>>>> YKScheduler(); 
	call	YKScheduler
	; >>>>> Line:	178
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	mov	sp, bp
	pop	bp
	ret
L_yakc_53:
	push	bp
	mov	bp, sp
	jmp	L_yakc_54
	ALIGN	2
YKEnterISR:
	; >>>>> Line:	182
	; >>>>> { 
	jmp	L_yakc_56
L_yakc_57:
	; >>>>> Line:	183
	; >>>>> ++YKInterruptDepth; 
	inc	word [YKInterruptDepth]
	mov	sp, bp
	pop	bp
	ret
L_yakc_56:
	push	bp
	mov	bp, sp
	jmp	L_yakc_57
	ALIGN	2
YKExitISR:
	; >>>>> Line:	190
	; >>>>> { 
	jmp	L_yakc_59
L_yakc_60:
	; >>>>> Line:	191
	; >>>>> --YKInterruptDepth; 
	dec	word [YKInterruptDepth]
	; >>>>> Line:	195
	; >>>>> if(YKInterruptDepth == 0 && kernelStarted && readyToStart) 
	mov	ax, word [YKInterruptDepth]
	test	ax, ax
	jne	L_yakc_61
	mov	ax, word [kernelStarted]
	test	ax, ax
	je	L_yakc_61
	mov	al, byte [readyToStart]
	test	al, al
	je	L_yakc_61
	; >>>>> Line:	197
	; >>>>> contextSaved = 1; 
	mov	byte [contextSaved], 1
	; >>>>> Line:	198
	; >>>>> YKScheduler(); 
	call	YKScheduler
L_yakc_61:
	mov	sp, bp
	pop	bp
	ret
L_yakc_59:
	push	bp
	mov	bp, sp
	jmp	L_yakc_60
	ALIGN	2
YKTickHandler:
	; >>>>> Line:	203
	; >>>>> { 
	jmp	L_yakc_63
L_yakc_64:
	; >>>>> Line:	205
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	206
	; >>>>> ++YKTickNum; 
	inc	word [YKTickNum]
	; >>>>> Line:	207
	; >>>>> for (i = 1; i <= 5; ++i) { 
	mov	word [bp-2], 1
	jmp	L_yakc_66
L_yakc_65:
	; >>>>> Line:	208
	; >>>>> if(YKTCBArray[i].state == DELAYED) { 
	mov	ax, word [bp-2]
	mov	cx, 14
	imul	cx
	add	ax, YKTCBArray
	mov	si, ax
	add	si, 4
	cmp	word [si], 1
	jne	L_yakc_69
	; >>>>> Line:	209
	; >>>>> if(YKTCBArray[i].delay == 1) { 
	mov	ax, word [bp-2]
	mov	cx, 14
	imul	cx
	add	ax, YKTCBArray
	mov	si, ax
	add	si, 8
	cmp	word [si], 1
	jne	L_yakc_70
	; >>>>> Line:	210
	; >>>>> YKTCBArray[i].state = READY; 
	mov	ax, word [bp-2]
	mov	cx, 14
	imul	cx
	add	ax, YKTCBArray
	mov	si, ax
	add	si, 4
	mov	word [si], 3
L_yakc_70:
	; >>>>> Line:	212
	; >>>>> --YKTCBArray[i].delay; 
	mov	ax, word [bp-2]
	mov	cx, 14
	imul	cx
	add	ax, YKTCBArray
	mov	si, ax
	add	si, 8
	dec	word [si]
L_yakc_69:
L_yakc_68:
	inc	word [bp-2]
L_yakc_66:
	cmp	word [bp-2], 5
	jle	L_yakc_65
L_yakc_67:
	mov	sp, bp
	pop	bp
	ret
L_yakc_63:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_64
	ALIGN	2
YKSemCreate:
	; >>>>> Line:	222
	; >>>>> { 
	jmp	L_yakc_72
L_yakc_73:
	; >>>>> Line:	223
	; >>>>> if(semIndex < (5 + 5)) 
	cmp	word [semIndex], 10
	jae	L_yakc_74
	; >>>>> Line:	225
	; >>>>> YKSemArray[semIndex].value = initialValue; 
	mov	ax, word [semIndex]
	shl	ax, 1
	mov	si, ax
	add	si, YKSemArray
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	226
	; >>>>> semIndex = semIndex + 1; 
	mov	ax, word [semIndex]
	inc	ax
	mov	word [semIndex], ax
	; >>>>> Line:	227
	; >>>>> return &YKSemArray[semIndex-1]; 
	mov	ax, word [semIndex]
	dec	ax
	shl	ax, 1
	add	ax, YKSemArray
	jmp	L_yakc_75
L_yakc_74:
	; >>>>> Line:	229
	; >>>>> return 0; 
	xor	ax, ax
L_yakc_75:
	mov	sp, bp
	pop	bp
	ret
L_yakc_72:
	push	bp
	mov	bp, sp
	jmp	L_yakc_73
	ALIGN	2
YKSemPend:
	; >>>>> Line:	233
	; >>>>> { 
	jmp	L_yakc_77
L_yakc_78:
	; >>>>> Line:	234
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	235
	; >>>>> if(semaphore->value <= 0) 
	mov	si, word [bp+4]
	cmp	word [si], 0
	jg	L_yakc_79
	; >>>>> Line:	237
	; >>>>> YKTCBArray[runningTask].state = SUSPENDED; 
	mov	al, byte [runningTask]
	xor	ah, ah
	mov	cx, 14
	imul	cx
	add	ax, YKTCBArray
	mov	si, ax
	add	si, 4
	mov	word [si], 2
	; >>>>> Line:	238
	; >>>>> YKTCBArray[runningTask].semaphore = semaphore; 
	mov	al, byte [runningTask]
	xor	ah, ah
	mov	cx, 14
	imul	cx
	add	ax, YKTCBArray
	mov	si, ax
	add	si, 10
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	239
	; >>>>> semaphore->value = semaphore->value - 1; 
	mov	si, word [bp+4]
	mov	ax, word [si]
	dec	ax
	mov	word [si], ax
	; >>>>> Line:	240
	; >>>>> contextSaved = 0; 
	mov	byte [contextSaved], 0
	; >>>>> Line:	241
	; >>>>> YKScheduler(); 
	call	YKScheduler
	jmp	L_yakc_80
L_yakc_79:
	; >>>>> Line:	245
	; >>>>> semaphore->value = semaphore->value - 1; 
	mov	si, word [bp+4]
	mov	ax, word [si]
	dec	ax
	mov	word [si], ax
L_yakc_80:
	; >>>>> Line:	247
	; >>>>> aphore = 0 
	call	YKExitMutex
	mov	sp, bp
	pop	bp
	ret
L_yakc_77:
	push	bp
	mov	bp, sp
	jmp	L_yakc_78
	ALIGN	2
YKSemPost:
	; >>>>> Line:	251
	; >>>>> { 
	jmp	L_yakc_82
L_yakc_83:
	; >>>>> Line:	255
	; >>>>> YKEnterMutex(); 
	mov	byte [bp-3], 100
	mov	byte [bp-4], 0
	; >>>>> Line:	255
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	256
	; >>>>> for(i = 1; i <= 5; i++) 
	mov	word [bp-2], 1
	jmp	L_yakc_85
L_yakc_84:
	; >>>>> Line:	258
	; >>>>> if(!YKTCBArray[i].inUse) 
	mov	ax, word [bp-2]
	mov	cx, 14
	imul	cx
	add	ax, YKTCBArray
	mov	si, ax
	add	si, 12
	mov	al, byte [si]
	test	al, al
	jne	L_yakc_88
	; >>>>> Line:	260
	; >>>>> break; 
	jmp	L_yakc_86
L_yakc_88:
	; >>>>> Line:	262
	; >>>>> if(YKTCBArray[i].semaphore == semaphore && YKTCBArray[i].priority < maxPriority) 
	mov	ax, word [bp-2]
	mov	cx, 14
	imul	cx
	add	ax, YKTCBArray
	mov	si, ax
	add	si, 10
	mov	ax, word [bp+4]
	cmp	ax, word [si]
	jne	L_yakc_89
	mov	ax, word [bp-2]
	mov	cx, 14
	imul	cx
	add	ax, YKTCBArray
	mov	si, ax
	add	si, 6
	mov	al, byte [si]
	cbw
	mov	dl, byte [bp-3]
	xor	dh, dh
	cmp	dx, ax
	jle	L_yakc_89
	; >>>>> Line:	264
	; >>>>> toRun = i; 
	mov	al, byte [bp-2]
	mov	byte [bp-4], al
	; >>>>> Line:	265
	; >>>>> maxPriority = YKTCBArray[i].priority; 
	mov	ax, word [bp-2]
	mov	cx, 14
	imul	cx
	add	ax, YKTCBArray
	mov	si, ax
	add	si, 6
	mov	al, byte [si]
	mov	byte [bp-3], al
L_yakc_89:
L_yakc_87:
	inc	word [bp-2]
L_yakc_85:
	cmp	word [bp-2], 5
	jle	L_yakc_84
L_yakc_86:
	; >>>>> Line:	268
	; >>>>> semaphore->value = semaphore->value + 1; 
	mov	si, word [bp+4]
	mov	ax, word [si]
	inc	ax
	mov	word [si], ax
	; >>>>> Line:	269
	; >>>>> if(toRun <= 0) 
	mov	al, byte [bp-4]
	test	al, al
	jne	L_yakc_90
	; >>>>> Line:	271
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	272
	; >>>>> return; 
	jmp	L_yakc_91
L_yakc_90:
	; >>>>> Line:	274
	; >>>>> YKTCBArray[toRun].state = READY; 
	mov	al, byte [bp-4]
	xor	ah, ah
	mov	cx, 14
	imul	cx
	add	ax, YKTCBArray
	mov	si, ax
	add	si, 4
	mov	word [si], 3
	; >>>>> Line:	275
	; >>>>> YKTCBArray[toRun].semaphore = 0 
	mov	al, byte [bp-4]
	xor	ah, ah
	mov	cx, 14
	imul	cx
	add	ax, YKTCBArray
	mov	si, ax
	add	si, 10
	mov	word [si], 0
	; >>>>> Line:	276
	; >>>>> if(YKInterruptDepth <= 0) 
	mov	ax, word [YKInterruptDepth]
	test	ax, ax
	jne	L_yakc_92
	; >>>>> Line:	278
	; >>>>> contextSaved = 0; 
	mov	byte [contextSaved], 0
	; >>>>> Line:	279
	; >>>>> YKScheduler(); 
	call	YKScheduler
L_yakc_92:
	; >>>>> Line:	281
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
L_yakc_91:
	mov	sp, bp
	pop	bp
	ret
L_yakc_82:
	push	bp
	mov	bp, sp
	sub	sp, 4
	jmp	L_yakc_83
	ALIGN	2
YKQCreate:
	; >>>>> Line:	290
	; >>>>> { 
	jmp	L_yakc_94
L_yakc_95:
	; >>>>> Line:	291
	; >>>>> if(qIndex < 5) 
	cmp	word [qIndex], 5
	jae	L_yakc_96
	; >>>>> Line:	293
	; >>>>> YKQArray[qIndex].start = start; 
	mov	ax, word [qIndex]
	mov	cx, 10
	imul	cx
	mov	si, ax
	add	si, YKQArray
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	294
	; >>>>> YKQArray[qIndex].headIndex = 0; 
	mov	ax, word [qIndex]
	mov	cx, 10
	imul	cx
	add	ax, YKQArray
	mov	si, ax
	add	si, 4
	mov	word [si], 0
	; >>>>> Line:	295
	; >>>>> YKQArray[qIndex].tailIndex = 0; 
	mov	ax, word [qIndex]
	mov	cx, 10
	imul	cx
	add	ax, YKQArray
	mov	si, ax
	add	si, 6
	mov	word [si], 0
	; >>>>> Line:	296
	; >>>>> YKQArray[qIndex].size = size; 
	mov	ax, word [qIndex]
	mov	cx, 10
	imul	cx
	add	ax, YKQArray
	mov	si, ax
	add	si, 2
	mov	ax, word [bp+6]
	mov	word [si], ax
	; >>>>> Line:	297
	; >>>>> YKQArray[qIndex].semaphore = YKSemCreate(0); 
	xor	ax, ax
	push	ax
	call	YKSemCreate
	add	sp, 2
	push	ax
	mov	ax, word [qIndex]
	mov	cx, 10
	imul	cx
	mov	dx, ax
	add	dx, YKQArray
	mov	si, dx
	add	si, 8
	pop	ax
	mov	word [si], ax
	; >>>>> Line:	298
	; >>>>> qIndex = qIndex + 1; 
	mov	ax, word [qIndex]
	inc	ax
	mov	word [qIndex], ax
	; >>>>> Line:	299
	; >>>>> return &YKQArray[qIndex-1]; 
	mov	ax, word [qIndex]
	dec	ax
	mov	cx, 10
	imul	cx
	add	ax, YKQArray
	jmp	L_yakc_97
L_yakc_96:
	; >>>>> Line:	301
	; >>>>> return 0; 
	xor	ax, ax
L_yakc_97:
	mov	sp, bp
	pop	bp
	ret
L_yakc_94:
	push	bp
	mov	bp, sp
	jmp	L_yakc_95
	ALIGN	2
YKQFull:
	; >>>>> Line:	305
	; >>>>> { 
	jmp	L_yakc_99
L_yakc_100:
	; >>>>> Line:	306
	; >>>>> if((queue->headIndex == queue->tailIndex + 1) || ((queue->headIndex == 0) 
	mov	si, word [bp+4]
	add	si, 6
	mov	ax, word [si]
	inc	ax
	mov	si, word [bp+4]
	add	si, 4
	mov	dx, word [si]
	cmp	dx, ax
	je	L_yakc_102
	mov	si, word [bp+4]
	add	si, 4
	mov	ax, word [si]
	test	ax, ax
	jne	L_yakc_101
	mov	si, word [bp+4]
	add	si, 2
	mov	ax, word [si]
	dec	ax
	mov	si, word [bp+4]
	add	si, 6
	mov	dx, word [si]
	cmp	dx, ax
	jne	L_yakc_101
L_yakc_102:
	; >>>>> Line:	308
	; >>>>> return 1; 
	mov	ax, 1
	jmp	L_yakc_103
L_yakc_101:
	; >>>>> Line:	310
	; >>>>> return 0; 
	xor	ax, ax
L_yakc_103:
	mov	sp, bp
	pop	bp
	ret
L_yakc_99:
	push	bp
	mov	bp, sp
	jmp	L_yakc_100
	ALIGN	2
YKQEmpty:
	; >>>>> Line:	314
	; >>>>> { 
	jmp	L_yakc_105
L_yakc_106:
	; >>>>> Line:	316
	; >>>>> if(queue->tailIndex == queue->headIndex) 
	mov	si, word [bp+4]
	add	si, 6
	mov	di, word [bp+4]
	add	di, 4
	mov	ax, word [di]
	cmp	ax, word [si]
	jne	L_yakc_107
	; >>>>> Line:	318
	; >>>>> return 1; 
	mov	ax, 1
	jmp	L_yakc_108
L_yakc_107:
	; >>>>> Line:	320
	; >>>>> return 0; 
	xor	ax, ax
L_yakc_108:
	mov	sp, bp
	pop	bp
	ret
L_yakc_105:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_106
	ALIGN	2
YKQPend:
	; >>>>> Line:	325
	; >>>>> { 
	jmp	L_yakc_110
L_yakc_111:
	; >>>>> Line:	327
	; >>>>> YKEnterMutex(); 
	mov	word [bp-2], 0
	; >>>>> Line:	327
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	328
	; >>>>> if(YKQEmpty(queue)) { 
	push	word [bp+4]
	call	YKQEmpty
	add	sp, 2
	test	ax, ax
	je	L_yakc_112
	; >>>>> Line:	330
	; >>>>> YKSemPend(queue->semaphore); 
	mov	si, word [bp+4]
	add	si, 8
	push	word [si]
	call	YKSemPend
	add	sp, 2
L_yakc_112:
	; >>>>> Line:	333
	; >>>>> returnVal = queue->start[queue->headIndex]; 
	mov	si, word [bp+4]
	add	si, 4
	mov	ax, word [si]
	shl	ax, 1
	mov	si, ax
	mov	di, word [bp+4]
	add	si, word [di]
	mov	ax, word [si]
	mov	word [bp-2], ax
	; >>>>> Line:	334
	; >>>>> queue->headIndex = (queue->headIndex + 1) % queue->size; 
	mov	si, word [bp+4]
	add	si, 4
	mov	ax, word [si]
	inc	ax
	xor	dx, dx
	mov	si, word [bp+4]
	add	si, 2
	div	word [si]
	mov	ax, dx
	mov	si, word [bp+4]
	add	si, 4
	mov	word [si], ax
	; >>>>> Line:	340
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	341
	; >>>>> return returnVal; 
	mov	ax, word [bp-2]
L_yakc_113:
	mov	sp, bp
	pop	bp
	ret
L_yakc_110:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_111
L_yakc_115:
	DB	0
	ALIGN	2
YKQPost:
	; >>>>> Line:	346
	; >>>>> { 
	jmp	L_yakc_116
L_yakc_117:
	; >>>>> Line:	349
	; >>>>> YKEnterMutex(); 
	mov	byte [bp-1], 0
	; >>>>> Line:	349
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	350
	; >>>>> if(YKQFull(queue)) { 
	push	word [bp+4]
	call	YKQFull
	add	sp, 2
	test	ax, ax
	je	L_yakc_118
	; >>>>> Line:	351
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	352
	; >>>>> return 0; 
	xor	ax, ax
	jmp	L_yakc_119
L_yakc_118:
	; >>>>> Line:	354
	; >>>>> if(YKQEmpty(queue) && notFirst) { 
	push	word [bp+4]
	call	YKQEmpty
	add	sp, 2
	test	ax, ax
	je	L_yakc_120
	mov	al, byte [L_yakc_115]
	test	al, al
	je	L_yakc_120
	; >>>>> Line:	355
	; >>>>> wasEmpty = 1; 
	mov	byte [bp-1], 1
L_yakc_120:
	; >>>>> Line:	357
	; >>>>> notFirst = 1; 
	mov	byte [L_yakc_115], 1
	; >>>>> Line:	358
	; >>>>> queue->start[queue->tailIndex] = msg; 
	mov	si, word [bp+4]
	add	si, 6
	mov	ax, word [si]
	shl	ax, 1
	mov	si, ax
	mov	di, word [bp+4]
	add	si, word [di]
	mov	ax, word [bp+6]
	mov	word [si], ax
	; >>>>> Line:	364
	; >>>>> queue->tailIndex = (queue->tailIndex + 1) % queue->size; 
	mov	si, word [bp+4]
	add	si, 6
	mov	ax, word [si]
	inc	ax
	xor	dx, dx
	mov	si, word [bp+4]
	add	si, 2
	div	word [si]
	mov	ax, dx
	mov	si, word [bp+4]
	add	si, 6
	mov	word [si], ax
	; >>>>> Line:	366
	; >>>>> if(wasEmpty) { 
	mov	al, byte [bp-1]
	test	al, al
	je	L_yakc_121
	; >>>>> Line:	367
	; >>>>> YKSemPost(queue->semaphore); 
	mov	si, word [bp+4]
	add	si, 8
	push	word [si]
	call	YKSemPost
	add	sp, 2
L_yakc_121:
	; >>>>> Line:	370
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	371
	; >>>>> return 1; 
	mov	ax, 1
L_yakc_119:
	mov	sp, bp
	pop	bp
	ret
L_yakc_116:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_117
	ALIGN	2
YKCtxSwCount:
	TIMES	2 db 0
YKIdleCount:
	TIMES	2 db 0
YKTickNum:
	TIMES	2 db 0
IdleStk:
	TIMES	512 db 0
currentTask:
	TIMES	2 db 0
nextTask:
	TIMES	2 db 0
YKTCBArray:
	TIMES	84 db 0
YKSemArray:
	TIMES	20 db 0
YKQArray:
	TIMES	50 db 0
;Kernel routines written in assembly

YKEnterMutex:
	cli
	ret

YKExitMutex:
	sti
	ret

YKDispatcherFirst:
	mov		bx, [nextTask]
	mov 	sp, [bx + 2]
	pop		ds
	pop 	es
	pop 	di
	pop 	si
	pop 	dx
	pop 	cx
	pop 	bx
	pop 	ax
	pop 	bp
	iret

YKDispatcher:
	pushf
	push	cs
	push	word[bp+2]
	push 	bp
	push 	ax
	push 	bx
	push 	cx
	push 	dx
	push 	si
	push 	di
	push 	es
	push 	ds
	;call pushed

	mov 	bx, [currentTask]
	mov		[bx + 2], sp

	mov		bx, [nextTask]
	mov 	sp, [bx + 2]
	pop		ds
	pop 	es
	pop 	di
	pop 	si
 	pop 	dx
	pop 	cx
  pop 	bx
  pop 	ax
	pop 	bp
	;call popped
  iret

YKCreateContext:
	push	bp
	mov		bp, sp
	push  word[bp + 4]
	mov		[bp + 4], sp
	pop 	sp
	push	word[FLAGS_MASK]
	push 	cs
	push	word[bp + 6]
	push 	bp
	push 	ax
	push 	bx
	push 	cx
	push 	dx
	push 	si
	push 	di
	push 	es
	push 	ds

	mov		sp, [bp + 4]
	pop 	bp
	pop		bp
	ret

YKDispatcherNoSave:
	mov 	bx, [currentTask]
	add		sp, 14
	mov		[bx + 2], sp

	mov		bx, [nextTask]
	mov 	sp, [bx + 2]
	pop		ds
	pop 	es
	pop 	di
	pop 	si
	pop 	dx
	pop 	cx
	pop 	bx
	pop 	ax
	pop 	bp
	;call popped
	iret
; Generated by c86 (BYU-NASM) 5.1 (beta) from lab6app.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
L_lab6app_5:
	DB	"Max: ",0
L_lab6app_4:
	DB	"Min: ",0
L_lab6app_3:
	DB	0x9,0
L_lab6app_2:
	DB	"Ticks: ",0
L_lab6app_1:
	DB	"! Dropped msgs: tick ",0
	ALIGN	2
ATask:
	; >>>>> Line:	26
	; >>>>> { 
	jmp	L_lab6app_6
L_lab6app_7:
	; >>>>> Line:	30
	; >>>>> min = 100; 
	mov	word [bp-4], 100
	; >>>>> Line:	31
	; >>>>> max = 0; 
	mov	word [bp-6], 0
	; >>>>> Line:	32
	; >>>>> count = 0; 
	mov	word [bp-8], 0
	; >>>>> Line:	34
	; >>>>> while (1) 
	jmp	L_lab6app_9
L_lab6app_8:
	; >>>>> Line:	36
	; >>>>> tmp = (struct msg *) YKQPend(MsgQPtr); 
	push	word [MsgQPtr]
	call	YKQPend
	add	sp, 2
	mov	word [bp-2], ax
	; >>>>> Line:	38
	; >>>>> if (tmp->tick != count+1) 
	mov	ax, word [bp-8]
	inc	ax
	mov	si, word [bp-2]
	mov	dx, word [si]
	cmp	dx, ax
	je	L_lab6app_11
	; >>>>> Line:	40
	; >>>>> print("! Dropped msgs: tick ", 21); 
	mov	ax, 21
	push	ax
	mov	ax, L_lab6app_1
	push	ax
	call	print
	add	sp, 4
	; >>>>> Line:	41
	; >>>>> if (tmp->tick - (count+1) > 1) { 
	mov	si, word [bp-2]
	mov	ax, word [si]
	sub	ax, word [bp-8]
	dec	ax
	cmp	ax, 1
	jle	L_lab6app_12
	; >>>>> Line:	42
	; >>>>> printInt(count+1); 
	mov	ax, word [bp-8]
	inc	ax
	push	ax
	call	printInt
	add	sp, 2
	; >>>>> Line:	43
	; >>>>> printChar('-'); 
	mov	al, 45
	push	ax
	call	printChar
	add	sp, 2
	; >>>>> Line:	44
	; >>>>> printInt(tmp->tick-1); 
	mov	si, word [bp-2]
	mov	ax, word [si]
	dec	ax
	push	ax
	call	printInt
	add	sp, 2
	; >>>>> Line:	45
	; >>>>> Int(max); 
	call	printNewLine
	jmp	L_lab6app_13
L_lab6app_12:
	; >>>>> Line:	48
	; >>>>> printInt(tmp->tick-1); 
	mov	si, word [bp-2]
	mov	ax, word [si]
	dec	ax
	push	ax
	call	printInt
	add	sp, 2
	; >>>>> Line:	49
	; >>>>> printNewLine(); 
	call	printNewLine
L_lab6app_13:
L_lab6app_11:
	; >>>>> Line:	54
	; >>>>> count = tmp->tick; 
	mov	si, word [bp-2]
	mov	ax, word [si]
	mov	word [bp-8], ax
	; >>>>> Line:	57
	; >>>>> if (tmp->data < min) 
	mov	si, word [bp-2]
	add	si, 2
	mov	ax, word [bp-4]
	cmp	ax, word [si]
	jle	L_lab6app_14
	; >>>>> Line:	58
	; >>>>> min = tmp->data; 
	mov	si, word [bp-2]
	add	si, 2
	mov	ax, word [si]
	mov	word [bp-4], ax
L_lab6app_14:
	; >>>>> Line:	59
	; >>>>> if (tmp->data > max) 
	mov	si, word [bp-2]
	add	si, 2
	mov	ax, word [bp-6]
	cmp	ax, word [si]
	jge	L_lab6app_15
	; >>>>> Line:	60
	; >>>>> max = tmp->data; 
	mov	si, word [bp-2]
	add	si, 2
	mov	ax, word [si]
	mov	word [bp-6], ax
L_lab6app_15:
	; >>>>> Line:	63
	; >>>>> print("Ticks: ", 7); 
	mov	ax, 7
	push	ax
	mov	ax, L_lab6app_2
	push	ax
	call	print
	add	sp, 4
	; >>>>> Line:	64
	; >>>>> printInt(count); 
	push	word [bp-8]
	call	printInt
	add	sp, 2
	; >>>>> Line:	65
	; >>>>> print("\t", 1); 
	mov	ax, 1
	push	ax
	mov	ax, L_lab6app_3
	push	ax
	call	print
	add	sp, 4
	; >>>>> Line:	66
	; >>>>> print("Min: ", 5); 
	mov	ax, 5
	push	ax
	mov	ax, L_lab6app_4
	push	ax
	call	print
	add	sp, 4
	; >>>>> Line:	67
	; >>>>> printInt(min); 
	push	word [bp-4]
	call	printInt
	add	sp, 2
	; >>>>> Line:	68
	; >>>>> print("\t", 1); 
	mov	ax, 1
	push	ax
	mov	ax, L_lab6app_3
	push	ax
	call	print
	add	sp, 4
	; >>>>> Line:	69
	; >>>>> print("Max: ", 5); 
	mov	ax, 5
	push	ax
	mov	ax, L_lab6app_5
	push	ax
	call	print
	add	sp, 4
	; >>>>> Line:	70
	; >>>>> printInt(max); 
	push	word [bp-6]
	call	printInt
	add	sp, 2
	; >>>>> Line:	71
	; >>>>> printNewLine(); 
	call	printNewLine
L_lab6app_9:
	jmp	L_lab6app_8
L_lab6app_10:
	mov	sp, bp
	pop	bp
	ret
L_lab6app_6:
	push	bp
	mov	bp, sp
	sub	sp, 8
	jmp	L_lab6app_7
	ALIGN	2
BTask:
	; >>>>> Line:	76
	; >>>>> { 
	jmp	L_lab6app_17
L_lab6app_18:
	; >>>>> Line:	80
	; >>>>> curval = 1001; 
	mov	word [bp-4], 1001
	; >>>>> Line:	81
	; >>>>> chcount = 0; 
	mov	word [bp-10], 0
	; >>>>> Line:	83
	; >>>>> while (1) 
	jmp	L_lab6app_20
L_lab6app_19:
	; >>>>> Line:	85
	; >>>>> YKDelayTask(2); 
	mov	ax, 2
	push	ax
	call	YKDelayTask
	add	sp, 2
	; >>>>> Line:	87
	; >>>>> if (GlobalFlag == 1) 
	cmp	word [GlobalFlag], 1
	jne	L_lab6app_22
	; >>>>> Line:	89
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	90
	; >>>>> busycount = YKTickNum; 
	mov	ax, word [YKTickNum]
	mov	word [bp-2], ax
	; >>>>> Line:	91
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	93
	; >>>>> while (1) 
	jmp	L_lab6app_24
L_lab6app_23:
	; >>>>> Line:	95
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	96
	; >>>>> tickNum = YKTickNum; 
	mov	ax, word [YKTickNum]
	mov	word [bp-12], ax
	; >>>>> Line:	97
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	98
	; >>>>> if(tickNum >= busycount + 5) break; 
	mov	ax, word [bp-2]
	add	ax, 5
	mov	dx, word [bp-12]
	cmp	dx, ax
	jb	L_lab6app_26
	; >>>>> Line:	98
	; >>>>> if(tickNum >= busycount + 5) break; 
	jmp	L_lab6app_25
L_lab6app_26:
	; >>>>> Line:	100
	; >>>>> 0; 
	add	word [bp-4], 2
	; >>>>> Line:	101
	; >>>>> flag = 0; 
	mov	word [bp-8], 0
	; >>>>> Line:	102
	; >>>>> for (j = 3; (j*j) < curval; j += 2) 
	mov	word [bp-6], 3
	jmp	L_lab6app_28
L_lab6app_27:
	; >>>>> Line:	104
	; >>>>> if (curval % j == 0) 
	mov	ax, word [bp-4]
	cwd
	idiv	word [bp-6]
	mov	ax, dx
	test	ax, ax
	jne	L_lab6app_31
	; >>>>> Line:	106
	; >>>>> flag = 1; 
	mov	word [bp-8], 1
	; >>>>> Line:	107
	; >>>>> break; 
	jmp	L_lab6app_29
L_lab6app_31:
L_lab6app_30:
	add	word [bp-6], 2
L_lab6app_28:
	mov	ax, word [bp-6]
	imul	word [bp-6]
	mov	dx, word [bp-4]
	cmp	dx, ax
	jg	L_lab6app_27
L_lab6app_29:
	; >>>>> Line:	110
	; >>>>> if (!flag) 
	mov	ax, word [bp-8]
	test	ax, ax
	jne	L_lab6app_32
	; >>>>> Line:	112
	; >>>>> printChar('.'); 
	mov	al, 46
	push	ax
	call	printChar
	add	sp, 2
	; >>>>> Line:	113
	; >>>>> if (++chcount > 75) 
	mov	ax, word [bp-10]
	inc	ax
	mov	word [bp-10], ax
	cmp	ax, 75
	jle	L_lab6app_33
	; >>>>> Line:	115
	; >>>>> printNewLine(); 
	call	printNewLine
	; >>>>> Line:	116
	; >>>>> chcount = 0; 
	mov	word [bp-10], 0
L_lab6app_33:
L_lab6app_32:
L_lab6app_24:
	jmp	L_lab6app_23
L_lab6app_25:
	; >>>>> Line:	120
	; >>>>> printNewLine(); 
	call	printNewLine
	; >>>>> Line:	121
	; >>>>> chcount = 0; 
	mov	word [bp-10], 0
	; >>>>> Line:	122
	; >>>>> GlobalFlag = 0; 
	mov	word [GlobalFlag], 0
L_lab6app_22:
L_lab6app_20:
	jmp	L_lab6app_19
L_lab6app_21:
	mov	sp, bp
	pop	bp
	ret
L_lab6app_17:
	push	bp
	mov	bp, sp
	sub	sp, 12
	jmp	L_lab6app_18
L_lab6app_39:
	DB	"% >>>>>",0xD,0xA,0
L_lab6app_38:
	DB	", CPU usage: ",0
L_lab6app_37:
	DB	"<<<<< Context switches: ",0
L_lab6app_36:
	DB	"Determining CPU capacity",0xD,0xA,0
L_lab6app_35:
	DB	"Welcome to the YAK kernel",0xD,0xA,0
	ALIGN	2
STask:
	; >>>>> Line:	128
	; >>>>> { 
	jmp	L_lab6app_40
L_lab6app_41:
	; >>>>> Line:	132
	; >>>>> YKDelayTask(1); 
	mov	ax, 1
	push	ax
	call	YKDelayTask
	add	sp, 2
	; >>>>> Line:	133
	; >>>>> printString("Welcome to the YAK kernel\r\n"); 
	mov	ax, L_lab6app_35
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	134
	; >>>>> printString("Determining CPU capacity\r\n"); 
	mov	ax, L_lab6app_36
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	135
	; >>>>> YKDelayTask(1); 
	mov	ax, 1
	push	ax
	call	YKDelayTask
	add	sp, 2
	; >>>>> Line:	136
	; >>>>> YKIdleCount = 0; 
	mov	word [YKIdleCount], 0
	; >>>>> Line:	137
	; >>>>> YKDelayTask(5); 
	mov	ax, 5
	push	ax
	call	YKDelayTask
	add	sp, 2
	; >>>>> Line:	138
	; >>>>> max = YKIdleCount / 25; 
	mov	ax, word [YKIdleCount]
	xor	dx, dx
	mov	cx, 25
	div	cx
	mov	word [bp-2], ax
	; >>>>> Line:	139
	; >>>>> YKIdleCount = 0; 
	mov	word [YKIdleCount], 0
	; >>>>> Line:	141
	; >>>>> YKNewTask(BTask, (void *) &BTaskStk[512], 10); 
	mov	al, 10
	push	ax
	mov	ax, (BTaskStk+1024)
	push	ax
	mov	ax, BTask
	push	ax
	call	YKNewTask
	add	sp, 6
	; >>>>> Line:	142
	; >>>>> YKNewTask(ATask, 
	mov	al, 20
	push	ax
	mov	ax, (ATaskStk+1024)
	push	ax
	mov	ax, ATask
	push	ax
	call	YKNewTask
	add	sp, 6
	; >>>>> Line:	144
	; >>>>> while (1) 
	jmp	L_lab6app_43
L_lab6app_42:
	; >>>>> Line:	146
	; >>>>> YKDelayTask(20); 
	mov	ax, 20
	push	ax
	call	YKDelayTask
	add	sp, 2
	; >>>>> Line:	148
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	149
	; >>>>> switchCount = YKCtxSwCount; 
	mov	ax, word [YKCtxSwCount]
	mov	word [bp-4], ax
	; >>>>> Line:	150
	; >>>>> idleCount = YKIdleCount; 
	mov	ax, word [YKIdleCount]
	mov	word [bp-6], ax
	; >>>>> Line:	151
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	153
	; >>>>> printString("<<<<< Context switches: "); 
	mov	ax, L_lab6app_37
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	154
	; >>>>> printInt((int)switchCount); 
	push	word [bp-4]
	call	printInt
	add	sp, 2
	; >>>>> Line:	155
	; >>>>> printString(", CPU usage: "); 
	mov	ax, L_lab6app_38
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	156
	; >>>>> tmp = (int) (idleCount/max); 
	mov	ax, word [bp-6]
	xor	dx, dx
	div	word [bp-2]
	mov	word [bp-8], ax
	; >>>>> Line:	157
	; >>>>> printInt(100-tmp); 
	mov	ax, 100
	sub	ax, word [bp-8]
	push	ax
	call	printInt
	add	sp, 2
	; >>>>> Line:	158
	; >>>>> printString("% >>>>>\r\n"); 
	mov	ax, L_lab6app_39
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	160
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	161
	; >>>>> YKCtxSwCount = 0; 
	mov	word [YKCtxSwCount], 0
	; >>>>> Line:	162
	; >>>>> YKIdleCount = 0; 
	mov	word [YKIdleCount], 0
	; >>>>> Line:	163
	; >>>>> YKExitMute 
	call	YKExitMutex
L_lab6app_43:
	jmp	L_lab6app_42
L_lab6app_44:
	mov	sp, bp
	pop	bp
	ret
L_lab6app_40:
	push	bp
	mov	bp, sp
	sub	sp, 8
	jmp	L_lab6app_41
	ALIGN	2
main:
	; >>>>> Line:	168
	; >>>>> { 
	jmp	L_lab6app_46
L_lab6app_47:
	; >>>>> Line:	169
	; >>>>> YKInitialize(); 
	call	YKInitialize
	; >>>>> Line:	172
	; >>>>> GlobalFlag = 0; 
	mov	word [GlobalFlag], 0
	; >>>>> Line:	173
	; >>>>> MsgQPtr = YKQCreate(MsgQ, 10); 
	mov	ax, 10
	push	ax
	mov	ax, MsgQ
	push	ax
	call	YKQCreate
	add	sp, 4
	mov	word [MsgQPtr], ax
	; >>>>> Line:	174
	; >>>>> YKNewTask(STask, (void *) &STaskStk[512], 30); 
	mov	al, 30
	push	ax
	mov	ax, (STaskStk+1024)
	push	ax
	mov	ax, STask
	push	ax
	call	YKNewTask
	add	sp, 6
	; >>>>> Line:	176
	; >>>>> YKRun(); 
	call	YKRun
	mov	sp, bp
	pop	bp
	ret
L_lab6app_46:
	push	bp
	mov	bp, sp
	jmp	L_lab6app_47
	ALIGN	2
MsgArray:
	TIMES	80 db 0
ATaskStk:
	TIMES	1024 db 0
BTaskStk:
	TIMES	1024 db 0
STaskStk:
	TIMES	1024 db 0
GlobalFlag:
	TIMES	2 db 0
MsgQ:
	TIMES	20 db 0
MsgQPtr:
	TIMES	2 db 0
