; Generated by c86 (BYU-NASM) 5.1 (beta) from myinth.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
	ALIGN	2
ticks:
	DW	0
L_myinth_1:
	DW	0
L_myinth_2:
	DW	0
L_myinth_3:
	DB	"  TickISR: queue overflow! ",0xA,0
	ALIGN	2
tickHandler:
	; >>>>> Line:	12
	; >>>>> { 
	jmp	L_myinth_4
L_myinth_5:
	; >>>>> Line:	17
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	18
	; >>>>> val = ++ticks; 
	mov	ax, word [ticks]
	inc	ax
	mov	word [ticks], ax
	mov	word [bp-2], ax
	; >>>>> Line:	19
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	23
	; >>>>> MsgArray[next].tick = YKTickNum; 
	mov	ax, word [L_myinth_1]
	shl	ax, 1
	shl	ax, 1
	mov	si, ax
	add	si, MsgArray
	mov	ax, word [YKTickNum]
	mov	word [si], ax
	; >>>>> Line:	24
	; >>>>> data = (data + 89) % 100; 
	mov	ax, word [L_myinth_2]
	add	ax, 89
	cwd
	mov	cx, 100
	idiv	cx
	mov	ax, dx
	mov	word [L_myinth_2], ax
	; >>>>> Line:	25
	; >>>>> MsgArray[next].data = data; 
	mov	ax, word [L_myinth_1]
	shl	ax, 1
	shl	ax, 1
	add	ax, MsgArray
	mov	si, ax
	add	si, 2
	mov	ax, word [L_myinth_2]
	mov	word [si], ax
	; >>>>> Line:	26
	; >>>>> if (YKQPost(MsgQPtr, (void *) &(MsgArray[next])) == 0) 
	mov	ax, word [L_myinth_1]
	shl	ax, 1
	shl	ax, 1
	add	ax, MsgArray
	push	ax
	push	word [MsgQPtr]
	call	YKQPost
	add	sp, 4
	test	ax, ax
	jne	L_myinth_6
	; >>>>> Line:	28
	; >>>>> printString("  TickISR: queue overflow! \n"); 
	mov	ax, L_myinth_3
	push	ax
	call	printString
	add	sp, 2
	jmp	L_myinth_7
L_myinth_6:
	; >>>>> Line:	30
	; >>>>> else if (++next >= 20) 
	mov	ax, word [L_myinth_1]
	inc	ax
	mov	word [L_myinth_1], ax
	cmp	ax, 20
	jl	L_myinth_8
	; >>>>> Line:	32
	; >>>>> next = 0; 
	mov	word [L_myinth_1], 0
L_myinth_8:
L_myinth_7:
	mov	sp, bp
	pop	bp
	ret
L_myinth_4:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_myinth_5
	ALIGN	2
keyboardHandler:
	; >>>>> Line:	37
	; >>>>> { 
	jmp	L_myinth_10
L_myinth_11:
	; >>>>> Line:	38
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	39
	; >>>>> GlobalFlag = 1; 
	mov	word [GlobalFlag], 1
	; >>>>> Line:	40
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	mov	sp, bp
	pop	bp
	ret
L_myinth_10:
	push	bp
	mov	bp, sp
	jmp	L_myinth_11
