/*
***************************************************************
*                       INCLUDES.H
***************************************************************
*/

#include    <STDIO.H>
#include    <STRING.H>
#include    <CTYPE.H>
#include    <STDLIB.H>
#include    <CONIO.H>
#include    <DOS.H>

#include    "\SOFTWARE\UCOS\Ix86S\Ix86S.H"
#include    "OS_CFG.H"
#include    "\SOFTWARE\UCOS\SOURCE\UCOS.H"
