; Generated by c86 (BYU-NASM) 5.1 (beta) from lab1.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
L_lab1_4:
	DB	"Result 3 is: ",0
L_lab1_3:
	DB	"Result 2 is: ",0
L_lab1_2:
	DB	"Result 1 is: ",0
L_lab1_1:
	DB	"Hello, world!",0xD,0xA,0
	ALIGN	2
main:
	; >>>>> Line:	8
	; >>>>> { 
	jmp	L_lab1_5
L_lab1_6:
	; >>>>> Line:	9
	; >>>>> gvar = 0; 
	mov	word [gvar], 0
	; >>>>> Line:	11
	; >>>>> printString("Hello, world!\r\n"); 
	mov	ax, L_lab1_1
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	13
	; >>>>> gvar = AsmFunction(10, 35, 3, 123, 100); 
	mov	ax, 100
	push	ax
	mov	ax, 123
	push	ax
	mov	al, 3
	push	ax
	mov	al, 35
	push	ax
	mov	ax, 10
	push	ax
	call	AsmFunction
	add	sp, 10
	mov	word [gvar], ax
	; >>>>> Line:	14
	; >>>>> print("Result 1 is: ", 13); 
	mov	ax, 13
	push	ax
	mov	ax, L_lab1_2
	push	ax
	call	print
	add	sp, 4
	; >>>>> Line:	15
	; >>>>> printInt(gvar); 
	push	word [gvar]
	call	printInt
	add	sp, 2
	; >>>>> Line:	16
	; >>>>> printNewLine(); 
	call	printNewLine
	; >>>>> Line:	18
	; >>>>> gvar = AsmFunction(14, -10, 126, 32, 15); 
	mov	ax, 15
	push	ax
	mov	ax, 32
	push	ax
	mov	al, 126
	push	ax
	mov	al, -10
	push	ax
	mov	ax, 14
	push	ax
	call	AsmFunction
	add	sp, 10
	mov	word [gvar], ax
	; >>>>> Line:	19
	; >>>>> print("Result 2 is: ", 13); 
	mov	ax, 13
	push	ax
	mov	ax, L_lab1_3
	push	ax
	call	print
	add	sp, 4
	; >>>>> Line:	20
	; >>>>> printInt(gvar); 
	push	word [gvar]
	call	printInt
	add	sp, 2
	; >>>>> Line:	21
	; >>>>> printNewLine(); 
	call	printNewLine
	; >>>>> Line:	23
	; >>>>> gvar = AsmFunction(17, 18, -121, 130, 118); 
	mov	ax, 118
	push	ax
	mov	ax, 130
	push	ax
	mov	al, -121
	push	ax
	mov	al, 18
	push	ax
	mov	ax, 17
	push	ax
	call	AsmFunction
	add	sp, 10
	mov	word [gvar], ax
	; >>>>> Line:	24
	; >>>>> print("Result 3 is: ", 13); 
	mov	ax, 13
	push	ax
	mov	ax, L_lab1_4
	push	ax
	call	print
	add	sp, 4
	; >>>>> Line:	25
	; >>>>> printInt(gvar); 
	push	word [gvar]
	call	printInt
	add	sp, 2
	; >>>>> Line:	26
	; >>>>> printNewLin 
	call	printNewLine
	; >>>>> Line:	28
	; >>>>> printNewLine(); 
	call	printNewLine
	mov	sp, bp
	pop	bp
	ret
L_lab1_5:
	push	bp
	mov	bp, sp
	jmp	L_lab1_6
	ALIGN	2
gvar:
	TIMES	2 db 0
